// Built-in starter question set the facilitator forks per event.
// Each entry produces one survey_questions row and zero or more
// trait_templates rows. For single/multi questions, a cohort
// template is emitted per option. For text questions, one discovery template.

import type { QuestionType } from "./traits";

export type SquareData = {
  answer: string; // option value; empty string for discovery
  squareText: string; // max 36 chars, shown on bingo card
  prompt: string; // conversation starter; empty for discovery
  enabled: boolean; // whether trait_template starts enabled
};

export type StarterQuestion = {
  prompt: string;
  type: QuestionType;
  options: string[] | null; // null for text
  squares: SquareData[];
};

export const STARTER_QUESTIONS: StarterQuestion[] = [
  {
    prompt: "What was your first programming language?",
    type: "single",
    options: [
      "Python",
      "JavaScript",
      "Java",
      "C / C++",
      "BASIC / Pascal",
      "Ruby",
      "PHP",
      "LLM English (Claude Code, Copilot, etc.)",
    ],
    squares: [
      { answer: "Python", squareText: "First language: Python", prompt: "What was the first thing you built in Python?", enabled: true },
      { answer: "JavaScript", squareText: "First language: JS", prompt: "How long before you rage-quit over a missing semicolon?", enabled: true },
      { answer: "Java", squareText: "First language: Java", prompt: "How many AbstractSingletonProxyFactoryBeans did you write before you questioned your choices?", enabled: true },
      { answer: "C / C++", squareText: "First language: C / C++", prompt: "What was the first thing you built in C/C++?", enabled: true },
      { answer: "BASIC / Pascal", squareText: "BASIC / Pascal veteran", prompt: "When did you realize you were old?", enabled: true },
      { answer: "Ruby", squareText: "First language: Ruby", prompt: "Do you still miss DHH on Twitter?", enabled: true },
      { answer: "PHP", squareText: "Survived PHP", prompt: "Show us on the doll where PHP hurt you.", enabled: true },
      { answer: "LLM English (Claude Code, Copilot, etc.)", squareText: "First language: English", prompt: "What is the coolest thing you have built using AI tools?", enabled: true },
    ],
  },
  {
    prompt: "What is the worst Teams habit?",
    type: "single",
    options: [
      "Replying in the channel instead of the thread",
      "Sending 'hi' then nothing",
      "Scheduling a meeting that could be a message",
      "Always recording",
      "Talking on mute repeatedly",
    ],
    squares: [
      { answer: "Replying in the channel instead of the thread", squareText: "Anti-channel reply", prompt: "How many times a week does this happen to you?", enabled: true },
      { answer: "Sending 'hi' then nothing", squareText: "Hates the lonely 'hi'", prompt: "Do you respond right away or let them sweat?", enabled: true },
      { answer: "Scheduling a meeting that could be a message", squareText: "Meeting = message", prompt: "What is the most unnecessary meeting you have ever been invited to?", enabled: true },
      { answer: "Always recording", squareText: "Always recording", prompt: "Have you ever rewatched a recording and caught something you wish you hadn't said?", enabled: true },
      { answer: "Talking on mute repeatedly", squareText: "Talks on mute", prompt: "What is the longest you have gone before someone told you?", enabled: true },
    ],
  },
  {
    prompt: "Which of these is most accurate?",
    type: "single",
    options: [
      "A hotdog is a sandwich",
      "Cereal is a soup",
      "A Pop-Tart is a ravioli",
      "Ketchup is a fruit jam",
    ],
    squares: [
      { answer: "A hotdog is a sandwich", squareText: "Hotdog = sandwich", prompt: "If a hotdog is a sandwich, is a taco a sandwich too? Where does it end?", enabled: true },
      { answer: "Cereal is a soup", squareText: "Cereal = soup", prompt: "Present your legal argument. We are listening.", enabled: true },
      { answer: "A Pop-Tart is a ravioli", squareText: "Pop-Tart = ravioli", prompt: "Does that make an uncrustable a dumpling? How deep does this go?", enabled: true },
      { answer: "Ketchup is a fruit jam", squareText: "Ketchup = fruit jam", prompt: "Walk us through the botanical analysis that got you here.", enabled: true },
    ],
  },
  {
    prompt: "Are you a morning person or night owl?",
    type: "single",
    options: ["Morning person", "Night owl", "Depends on the day"],
    squares: [
      { answer: "Morning person", squareText: "Morning person", prompt: "What ungodly hour do you wake up? Do you also enjoy running?", enabled: true },
      { answer: "Night owl", squareText: "Night owl", prompt: "What is the latest you have stayed up debugging something you swore would be a 5 minute fix?", enabled: true },
      { answer: "Depends on the day", squareText: "It depends", prompt: "What determines which version of you shows up?", enabled: false },
    ],
  },
  {
    prompt: "What is your dream vacation style?",
    type: "single",
    options: [
      "All-inclusive resort (do nothing)",
      "Backpacking / adventure travel",
      "Food and culture city trip",
      "Road trip",
      "Cabin in the middle of nowhere",
      "Theme parks",
    ],
    squares: [
      { answer: "All-inclusive resort (do nothing)", squareText: "Vacation: do nothing", prompt: "What is your drink order when you are doing absolutely nothing poolside?", enabled: true },
      { answer: "Backpacking / adventure travel", squareText: "Adventure traveler", prompt: "What is the most adventurous trip you have taken?", enabled: true },
      { answer: "Food and culture city trip", squareText: "Foodie traveler", prompt: "Best meal you have ever had on a trip?", enabled: true },
      { answer: "Road trip", squareText: "Road tripper", prompt: "What is the longest drive you have done in one stretch?", enabled: false },
      { answer: "Cabin in the middle of nowhere", squareText: "Off the grid vacationer", prompt: "How long before you check Slack anyway?", enabled: true },
      { answer: "Theme parks", squareText: "Theme park person", prompt: "Annual pass holder or casual? There is a right answer.", enabled: true },
    ],
  },
  {
    prompt: "What is your relationship with caffeine?",
    type: "single",
    options: [
      "Any way and lots of it",
      "I like my coffee like my pants — fancy",
      "Strictly tea, thanks",
      "It's an energy drink situation",
      "Caffeine is for the weak",
      "Only when Matthew sets a deadline",
    ],
    squares: [
      { answer: "Any way and lots of it", squareText: "Caffeine maximalist", prompt: "How many cups deep are you by standup?", enabled: true },
      { answer: "I like my coffee like my pants — fancy", squareText: "Fancy coffee order", prompt: "What is your current order? Be specific.", enabled: true },
      { answer: "Strictly tea, thanks", squareText: "Tea person", prompt: "What is your go-to tea? Do you have opinions about steep time?", enabled: true },
      { answer: "It's an energy drink situation", squareText: "Energy drink dependent", prompt: "What brand and how many per day? Be honest.", enabled: true },
      { answer: "Caffeine is for the weak", squareText: "Caffeine-free", prompt: "What dark magic keeps you going instead?", enabled: true },
      { answer: "Only when Matthew sets a deadline", squareText: "Deadline-fueled", prompt: "Tell us about the deadline that converted you.", enabled: true },
    ],
  },
  {
    prompt: "Any pets?",
    type: "multi",
    options: ["Dog", "Cat", "Other", "No pets"],
    squares: [
      { answer: "Dog", squareText: "Has a dog", prompt: "What breed? Show a photo if you have one!", enabled: true },
      { answer: "Cat", squareText: "Has a cat", prompt: "Does the cat sit on your keyboard during standups?", enabled: true },
      { answer: "Other", squareText: "Has an unusual pet", prompt: "What is it? We need the full story.", enabled: true },
      { answer: "No pets", squareText: "Pets belong in sanctuaries", prompt: "What is the closest you have come to caving and getting one?", enabled: true },
    ],
  },
  {
    prompt: "What is your go-to move when you are stuck on a problem?",
    type: "single",
    options: [
      "Take a walk",
      "Explain it to someone (or a rubber duck)",
      "Stare at the screen harder",
      "Shower / sleep on it",
      "Burn it down and start over",
    ],
    squares: [
      { answer: "Take a walk", squareText: "Walks it off", prompt: "What is the longest walk a bug has ever sent you on?", enabled: true },
      { answer: "Explain it to someone (or a rubber duck)", squareText: "Rubber duck debugger", prompt: "Do you have an actual rubber duck or do you just ambush a coworker?", enabled: true },
      { answer: "Stare at the screen harder", squareText: "Stares harder", prompt: "Has this ever actually worked? Even once?", enabled: true },
      { answer: "Shower / sleep on it", squareText: "Sleeps on it", prompt: "What is the wildest solution that came to you at 3am or in the shower?", enabled: true },
      { answer: "Burn it down and start over", squareText: "Burn it down", prompt: "What is the biggest thing you have ever scrapped and rewritten?", enabled: true },
    ],
  },
  {
    prompt: "What is an interest or hobby you have outside of work?",
    type: "text",
    options: null,
    squares: [
      { answer: "", squareText: "Learn someone's hobby", prompt: "", enabled: true },
    ],
  },
  {
    prompt: "Describe something on your desk right now (memento, decoration, snack stash, mystery cable pile — anything goes)",
    type: "text",
    options: null,
    squares: [
      { answer: "", squareText: "Learn someone's desk item", prompt: "", enabled: true },
    ],
  },
  {
    prompt: "Where did you grow up?",
    type: "text",
    options: null,
    squares: [
      { answer: "", squareText: "Learn where someone grew up", prompt: "", enabled: true },
    ],
  },
  {
    prompt: "What is your hottest tech take?",
    type: "single",
    options: [
      "Allbirds will be a great AI company",
      "The cloud is just someone else's space heater",
      "Python is just a very slow way to tell a GPU what to do",
      "Every 'Smart Home' is just an elaborate plan to lock you out during a Wi-Fi outage",
    ],
    squares: [
      { answer: "Allbirds will be a great AI company", squareText: "Allbirds AI believer", prompt: "How many pairs do you own and does that affect your analysis?", enabled: true },
      { answer: "The cloud is just someone else's space heater", squareText: "Cloud = space heater", prompt: "Have you ever actually been inside a data center? How warm was it?", enabled: true },
      { answer: "Python is just a very slow way to tell a GPU what to do", squareText: "Python is slow", prompt: "What language would you replace it with and how many enemies would that make?", enabled: true },
      { answer: "Every 'Smart Home' is just an elaborate plan to lock you out during a Wi-Fi outage", squareText: "Smart home skeptic", prompt: "Tell us about the time your smart home betrayed you.", enabled: true },
    ],
  },
  {
    prompt: "What is the most tabs you have had open at once?",
    type: "single",
    options: [
      "Under 10 (I have self control)",
      "10-30",
      "30-50",
      "50-100",
      "100+ (send help)",
    ],
    squares: [
      { answer: "Under 10 (I have self control)", squareText: "Under 10 tabs", prompt: "How does it feel to have your life together?", enabled: true },
      { answer: "10-30", squareText: "10-30 tabs", prompt: "The moderate middle. Do you also drive the speed limit?", enabled: false },
      { answer: "30-50", squareText: "30-50 tabs", prompt: "You are in the danger zone. Do you feel it?", enabled: false },
      { answer: "50-100", squareText: "50-100 tabs", prompt: "At what point did you stop closing them and just accept it?", enabled: false },
      { answer: "100+ (send help)", squareText: "100+ tabs open", prompt: "Do you also have 47 Teams channels unread right now?", enabled: true },
    ],
  },
  {
    prompt: "What is a hill you will die on that has nothing to do with tech?",
    type: "text",
    options: null,
    squares: [
      { answer: "", squareText: "Learn someone's non-tech hill", prompt: "", enabled: true },
    ],
  },
  {
    prompt: "What is the best thing you have binge-watched recently?",
    type: "text",
    options: null,
    squares: [
      { answer: "", squareText: "Get a show recommendation", prompt: "", enabled: true },
    ],
  },
];

// Realistic text-answer pools for seeding survey responses. Keyed by the exact
// question prompt so the seed action and dev-seed script can look up answers.
// Any text-type prompt missing from this map falls back to GENERIC_TEXT_POOL.
export const TEXT_ANSWER_POOLS: Record<string, string[]> = {
  "What is an interest or hobby you have outside of work?": [
    "bread baking",
    "bouldering",
    "urban sketching",
    "birdwatching",
    "home roasting coffee",
    "salsa dancing",
    "pottery",
    "trail running",
    "woodworking",
    "board game design",
    "open-water swimming",
    "film photography",
    "gardening",
    "ultimate frisbee",
    "fermenting hot sauce",
    "chess puzzles",
    "stand-up paddleboarding",
    "cooking Sichuan food",
    "restoring vintage bikes",
    "D&D campaigns",
    "knitting socks",
    "foraging mushrooms",
    "amateur astronomy",
    "can solve a Rubik's cube sub-2min",
    "play the theremin",
    "unicycle",
    "juggle four balls",
    "do a standing backflip",
    "identify birds by call",
    "whistle two notes at once",
    "parallel park a 24ft trailer",
    "draw a perfect freehand circle",
  ],
  "Describe something on your desk right now (memento, decoration, snack stash, mystery cable pile — anything goes)": [
    "a rubber duck wearing sunglasses",
    "a lava lamp from 2003",
    "a tiny cactus named Gerald",
    "a stress ball shaped like a brain",
    "an unopened energy drink from last week",
    "a Lego Millennium Falcon half-built",
    "a stack of sticky notes with existential quotes",
    "a mechanical keyboard I'm not using",
    "a vintage rotary phone",
    "a miniature zen garden that's mostly sand on the desk",
    "a framed photo of my cat judging me",
    "three different pairs of headphones",
    "a broken Rubik's cube",
    "a souvenir from a conference I don't remember attending",
    "a jar of hot sauce",
    "a Nerf gun for 'emergencies'",
    "a fidget spinner collection",
    "a bobblehead of someone I don't recognize",
    "a plant that should definitely be dead by now",
    "a stack of cables I'll 'definitely need someday'",
    "a coffee mug with a motivational quote I disagree with",
    "a tiny disco ball",
    "a foam finger from a sports team I don't follow",
    "a rock that I thought looked cool",
  ],
  "Where did you grow up?": [
    "Austin, TX",
    "Brooklyn, NY",
    "Seattle, WA",
    "Portland, OR",
    "Denver, CO",
    "small town in Vermont",
    "rural Ohio",
    "Toronto, Canada",
    "outside Chicago",
    "Dublin, Ireland",
    "Lagos, Nigeria",
    "Bangalore, India",
    "São Paulo, Brazil",
    "Berlin, Germany",
    "Tokyo suburbs",
    "Melbourne, Australia",
    "a farm in Iowa",
    "Miami, FL",
    "Mexico City",
    "northern California",
    "Boston area",
    "Edinburgh, Scotland",
    "Nairobi, Kenya",
    "Manila, Philippines",
    "Phoenix, AZ",
    "Minneapolis, MN",
    "Salt Lake City, UT",
    "Atlanta, GA",
    "Vancouver, BC",
    "Houston, TX",
    "San Diego, CA",
    "somewhere in New Jersey",
  ],
  "What is a hill you will die on that has nothing to do with tech?": [
    "cereal is a soup",
    "the oxford comma is non-negotiable",
    "pineapple belongs on pizza",
    "a hot dog is a taco, not a sandwich",
    "gif is pronounced with a hard G",
    "water is wet",
    "the toilet paper goes over, never under",
    "ranch dressing goes with everything",
    "Die Hard is a Christmas movie",
    "the book is always better than the movie",
    "you should always back into parking spots",
    "ketchup on eggs is fine, actually",
    "socks with sandals can work",
    "sparkling water is just angry water",
    "mayo does not belong on a burger",
    "breakfast for dinner is the best meal",
    "naps should be mandatory",
    "the window seat is always better",
    "you should never clap when the plane lands",
    "cats are better than dogs (fight me)",
    "dogs are better than cats (obviously)",
    "the middle seat person gets both armrests",
    "you should always salt your pasta water",
    "boneless wings are just chicken nuggets",
  ],
  "What is the best thing you have binge-watched recently?": [
    "Severance",
    "The Bear",
    "Shogun",
    "Fallout",
    "Baby Reindeer",
    "3 Body Problem",
    "Slow Horses",
    "Ripley",
    "True Detective: Night Country",
    "Beef",
    "The Last of Us",
    "Andor",
    "Abbott Elementary",
    "Hacks",
    "Only Murders in the Building",
    "The Diplomat",
    "Reacher",
    "House of the Dragon",
    "Yellowjackets",
    "The Gentlemen",
    "Silo",
    "For All Mankind",
    "Bad Sisters",
    "Lessons in Chemistry",
    "Mr. & Mrs. Smith",
    "The Morning Show",
    "Dark Matter",
    "Shrinking",
    "Poker Face",
    "Wednesday",
    "The White Lotus",
    "Succession (again)",
  ],
};

export const GENERIC_TEXT_POOL = [
  "something interesting",
  "hard to explain in one line",
  "you'd have to ask me in person",
  "it's a long story",
];
