-- IceBreakerBingo initial schema.
-- No RLS in v1 — every row is read/written by server code using the
-- service-role key; API routes enforce per-player / per-facilitator scope.

create extension if not exists "pgcrypto";

-- ─── enums ─────────────────────────────────────────────────────────────────
create type event_state as enum (
  'draft',
  'survey_open',
  'survey_closed',
  'curation_locked',
  'live',
  'ended'
);

create type question_type as enum (
  'single',
  'multi',
  'binary',
  'text',
  'numeric_bucket'
);

create type trait_kind as enum ('cohort', 'discovery');

create type bingo_line_type as enum ('row', 'col', 'diag');

create type prize_kind as enum (
  'first_across',
  'first_down',
  'first_diagonal',
  'first_blackout',
  'fastest_bingo',
  'unluckiest'
);

-- ─── facilitators ──────────────────────────────────────────────────────────
-- Password is scrypt, hashed app-side (see lib/password.ts).
create table facilitators (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

-- ─── events ────────────────────────────────────────────────────────────────
create table events (
  id uuid primary key default gen_random_uuid(),
  facilitator_id uuid not null references facilitators(id) on delete cascade,
  code text not null unique check (code = upper(code) and length(code) between 4 and 12),
  name text not null,
  starts_at timestamptz,
  state event_state not null default 'draft',
  survey_opened_at timestamptz,
  survey_closed_at timestamptz,
  curation_locked_at timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  reuse_unlocked boolean not null default false,
  reuse_unlocked_at timestamptz,
  created_at timestamptz not null default now()
);

create index events_facilitator_id_idx on events(facilitator_id);

-- ─── players ───────────────────────────────────────────────────────────────
-- access_code is a 96-bit url-safe random string; the credential is the URL.
-- qr_nonce is a separate random column embedded in the player's QR code.
create table players (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events(id) on delete cascade,
  display_name text not null,
  contact_handle text,
  access_code text not null,
  qr_nonce text not null unique,
  absent boolean not null default false,
  survey_submitted_at timestamptz,
  created_at timestamptz not null default now(),
  unique (event_id, access_code)
);

create index players_event_id_idx on players(event_id);

-- ─── survey questions ─────────────────────────────────────────────────────
create table survey_questions (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events(id) on delete cascade,
  prompt text not null,
  type question_type not null,
  options jsonb,      -- array of option strings for single/multi/binary
  position integer not null,
  created_at timestamptz not null default now(),
  unique (event_id, position)
);

create index survey_questions_event_id_idx on survey_questions(event_id);

-- ─── survey responses ──────────────────────────────────────────────────────
-- value is jsonb so it can hold strings, arrays, numbers uniformly.
create table survey_responses (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references players(id) on delete cascade,
  question_id uuid not null references survey_questions(id) on delete cascade,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  unique (player_id, question_id)
);

create index survey_responses_question_id_idx on survey_responses(question_id);

-- ─── trait templates ──────────────────────────────────────────────────────
-- Cohort: match_rule decides which players satisfy.
-- Discovery: no match_rule — any player with a non-empty answer to the
-- source question satisfies the square; reveal shows that answer.
create table trait_templates (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events(id) on delete cascade,
  question_id uuid not null references survey_questions(id) on delete cascade,
  kind trait_kind not null,
  match_rule jsonb,                              -- null for discovery
  square_text text not null check (length(square_text) <= 36),
  conversation_prompt text,                      -- nullable for discovery
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create index trait_templates_event_id_idx on trait_templates(event_id);
create index trait_templates_question_id_idx on trait_templates(question_id);

-- ─── player traits (materialized) ─────────────────────────────────────────
-- Regenerated by the card-gen job from survey_responses + trait_templates.
create table player_traits (
  player_id uuid not null references players(id) on delete cascade,
  trait_template_id uuid not null references trait_templates(id) on delete cascade,
  primary key (player_id, trait_template_id)
);

create index player_traits_template_id_idx on player_traits(trait_template_id);

-- ─── cards ────────────────────────────────────────────────────────────────
create table cards (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references players(id) on delete cascade unique,
  generated_at timestamptz not null default now()
);

create table card_squares (
  card_id uuid not null references cards(id) on delete cascade,
  position smallint not null check (position between 0 and 24),
  trait_template_id uuid references trait_templates(id) on delete restrict,
                                                -- null iff free space (position 12)
  primary key (card_id, position),
  check (
    (position = 12 and trait_template_id is null)
    or (position <> 12 and trait_template_id is not null)
  )
);

-- ─── claims ───────────────────────────────────────────────────────────────
-- idempotency_key is a client-generated UUID; repeats return the original row.
create table claims (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references cards(id) on delete cascade,
  position smallint not null check (position between 0 and 24 and position <> 12),
  via_player_id uuid not null references players(id) on delete restrict,
  trait_template_id uuid not null references trait_templates(id) on delete restrict,
  idempotency_key uuid not null,
  claimed_at timestamptz not null default now(),
  unique (card_id, position),
  unique (card_id, idempotency_key)
);

create index claims_via_player_id_idx on claims(via_player_id);

-- ─── bingos ───────────────────────────────────────────────────────────────
create table bingos (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references players(id) on delete cascade,
  card_id uuid not null references cards(id) on delete cascade,
  line_type bingo_line_type not null,
  line_index smallint not null,                  -- 0..4 for row/col, 0|1 for diag
  completed_at timestamptz not null default now(),
  triggering_claim_id uuid not null references claims(id) on delete restrict,
  unique (card_id, line_type, line_index)
);

create index bingos_player_id_idx on bingos(player_id);

-- ─── prize awards ─────────────────────────────────────────────────────────
-- Live prizes (first_*) are guarded by a unique partial index so only the
-- literal first row wins each. End-of-game prizes (fastest_bingo,
-- unluckiest) may have multiple rows on a tie.
create table prize_awards (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events(id) on delete cascade,
  prize prize_kind not null,
  player_id uuid not null references players(id) on delete cascade,
  awarded_at timestamptz not null default now(),
  detail jsonb
);

create unique index prize_awards_live_unique
  on prize_awards (event_id, prize)
  where prize in ('first_across','first_down','first_diagonal','first_blackout');

create index prize_awards_event_id_idx on prize_awards(event_id);
